### ISSUE TITLE
[PE-D][Tester D] [/edit :tag] Allows user to edit tags that do not exist

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T12-4/tp#121]
<i><video controls><source src="https://raw.githubusercontent.com/moguries/ped/main/files/e0cc3e5a-e900-4c73-8d33-74a2376dad12.mov" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/moguries/ped/main/files/e0cc3e5a-e900-4c73-8d33-74a2376dad12.mov</i>

Currently users are allowed to edit tags that do not exist, and edited person success message still shows. But the tag does not appear in person card (UI)

This might be a little confusing, as user might think they have successfully edited a tag when it actually doesn't exist D:

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: moguries/ped#4

**Comment by linnn-7** [comment]
Thank you!
