### ISSUE TITLE
[PE-D][Tester A] Clear Command not showing in User Guide but works in app

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T12-4/tp#153]
**Describe the bug**

The `clear` command is not a valid command refered to the User Guide, however when input `clear` all data is lost

**To Reproduce**
type `/clear` and press `Enter` in the command box

**Expected behavior**
Referring to the User Guide, as it is not a valid command, an error message should be shown

**Screenshots**

![image.png](https://raw.githubusercontent.com/fy17ohhh/ped/main/files/496c3d6e-628a-4403-8cad-a1ba2340414f.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: fy17ohhh/ped#13

**Comment by linnn-7** [comment]
Thank you for your feedback!
